---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  log_file: /var/log/chef-solo.log

platforms:
- name: opscode-ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      cpus: 2
      memory: 1024

suites:
- name: default
  run_list: "recipe[rs-cookbooks_ci::default]"
  attributes:
    rs-cookbooks_ci:
      jenkins:
        username: qa
        password: qapass
        user_full_name: White Team QA
        user_email: whiteqa@rightscale.com
        jobs:
          marker:
            git_project_description: Resource to create a visual marker in the Chef log based on a template
            git_repo: git://github.com/rightscale-cookbooks/marker.git
            git_project_url: https://github.com/rightscale-cookbooks/marker
        config:
          git_setup:
            git_username: rightscale-cookbooks-jenkins
            git_email:  cookbooks@rightscale.com
          jenkins_location:
            url: http://33.33.33.10:8080/
            email: name@mycompany.com
          ghprb:
            token: thisIsAFakeToken
            admins:
            - test-admin1
            - test-admin2
            - test-admin3
          webhook:
            bot_username: qabot

- name: jenkins
  run_list:
    - recipe[rs-cookbooks_ci::jenkins]
  attributes:
    rs-cookbooks_ci:
      jenkins:
        username: qa
        password: qapass
        user_full_name: White Team QA
        user_email: whiteqa@rightscale.com
        jobs:
          marker:
            git_description: Resource to create a visual marker in the Chef log based on a template
            git_repo: git://github.com/rightscale-cookbooks/marker.git
            git_project_url: https://github.com/rightscale-cookbooks/marker
        config:
            git_setup:
              username: rightscale-cookbooks-jenkins
              email:  cookbooks@rightscale.com
            jenkins_location:
              url: http://33.33.33.10:8080/
              email: name@mycompany.com
            # The token below refers to the Github Access Token, which you must generate for your account
            # The one inserted here is just a throwaway one and needs to be overridden
            ghprb:
              token: thisIsAFakeToken
              admins:
              - test-admin1
              - test-admin2
              - test-admin3
            webhook:
              bot_username: qabot
